#*****************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# recreate.tcl: Tcl script for re-creating project 'arty'
#
# Generated by Vivado on Sat Jan 05 22:26:10 PST 2019
# IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (recreate.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/fpga/arty/top/rtl/pulpemu_top.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/fpga/arty/arty.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/fpga/arty/arty.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32.xci"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/fpga/arty/top/xdc/arty_pulpino.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/include/riscv_defines.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/include/riscv_tracer_defines.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/include/apu_core_package.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/cluster_clock_gating.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_L0_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_alu.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_alu_div.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_apu_disp.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_compressed_decoder.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_controller.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_cs_registers.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_debug_unit.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_decoder.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_ex_stage.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_fetch_fifo.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_hwloop_controller.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_hwloop_regs.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_id_stage.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_if_stage.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_int_controller.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_load_store_unit.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_mult.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_prefetch_L0_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_prefetch_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_register_file_latch.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/riscv/riscv_core.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_tap_defines.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_tap_top.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/fpga/rtl/pulpino_wrap.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_axi_biu.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_axi_defines.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_defines.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_axi_module.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_defines.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_module.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_top.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adv_dbg_if.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb2per/apb2per.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_event_unit/apb_event_unit.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_fll_if/apb_fll_if.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_gpio/apb_gpio.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_i2c/i2c_master_defines.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_i2c/apb_i2c.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_node/apb_node.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_node/apb_node_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_pulpino/apb_pulpino.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/apb_spi_master.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_timer/apb_timer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi2apb/axi2apb.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi2apb/axi2apb32.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/axi2apb_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_AR_allocator.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_AW_allocator.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_ArbitrationTree.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_BR_allocator.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_BW_allocator.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_DW_allocator.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_FanInPrimitive_Req.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_RR_Flag_Req.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_address_decoder_AR.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_address_decoder_AW.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_address_decoder_BR.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_address_decoder_BW.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_address_decoder_DW.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_ar_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_aw_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_b_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/axi_mem_if_SP_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_multiplexer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_node.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/axi_node_intf_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_r_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_request_block.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_node/axi_response_block.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_slice.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/axi_slice_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/axi_spi_slave.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/axi_spi_slave_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice/axi_w_buffer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/boot_code.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/boot_rom_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/cluster_clock_inverter.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/cluster_clock_mux2.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/core2axi/core2axi.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/core2axi_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/core_region.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/generic_fifo.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_event_unit/generic_service_unit.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/instr_ram_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/periph_bus_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/peripherals.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/pulpino_top.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/ram_mux.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/rstgen.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_event_unit/sleep_unit.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/sp_ram_wrap.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_apb_if.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_clkgen.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_controller.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_fifo.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_rx.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_spi_master/spi_master_tx.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_controller.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_regs.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_rx.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_syncro.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_spi_slave/spi_slave_tx.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_timer/timer.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/apb_uart.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_clock_div.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_counter.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_edge_detect.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_fifo.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_input_filter.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_input_sync.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/slib_mv_filter.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/uart_baudgen.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/uart_interrupt.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/uart_receiver.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/apb/apb_uart/uart_transmitter.vhd"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/clk_rst_gen.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_lint_defines.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/pulp_clock_inverter.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/rtl/components/pulp_clock_mux2.sv"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_dout.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_din.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_full_detector.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_token_ring.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_data_buffer.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/axi/axi_slice_dc/dc_synchronizer.v"
#    "/home/kle/iBox/pr/pulp/Pulpino-for-dummies/pulpino/ips/adv_dbg_if/rtl/adbg_crc32.v"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "arty"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "recreate.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
#create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a35tcsg324-1
create_project ${_xil_proj_name_} "." -part xc7a35tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# (kle) debug
puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
puts "$origin_dir"
puts "$orig_proj_dir"
puts "$proj_dir"
puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++"


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tcsg324-1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "None" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "8" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "8" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "8" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "8" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "8" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "8" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "8" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/include/riscv_defines.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/include/riscv_tracer_defines.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/include/apu_core_package.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/cluster_clock_gating.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_L0_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_alu.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_alu_div.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_apu_disp.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_compressed_decoder.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_controller.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_cs_registers.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_debug_unit.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_decoder.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_ex_stage.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_fetch_fifo.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_hwloop_controller.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_hwloop_regs.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_id_stage.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_if_stage.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_int_controller.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_load_store_unit.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_mult.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_prefetch_L0_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_prefetch_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_register_file_latch.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/riscv/riscv_core.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_tap_defines.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_tap_top.v"] \
 [file normalize "${origin_dir}/../../pulpino/fpga/rtl/pulpino_wrap.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_axi_biu.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_axi_defines.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_defines.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_axi_module.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_defines.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_module.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_top.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adv_dbg_if.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb2per/apb2per.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_event_unit/apb_event_unit.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_fll_if/apb_fll_if.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_gpio/apb_gpio.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_i2c/i2c_master_defines.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_i2c/apb_i2c.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_node/apb_node.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_node/apb_node_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_pulpino/apb_pulpino.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/apb_spi_master.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_timer/apb_timer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi2apb/axi2apb.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi2apb/axi2apb32.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/axi2apb_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_AR_allocator.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_AW_allocator.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_ArbitrationTree.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_BR_allocator.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_BW_allocator.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_DW_allocator.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_FanInPrimitive_Req.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_RR_Flag_Req.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_address_decoder_AR.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_address_decoder_AW.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_address_decoder_BR.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_address_decoder_BW.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_address_decoder_DW.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_ar_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_aw_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_b_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/axi_mem_if_SP_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_multiplexer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_node.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/axi_node_intf_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_r_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_request_block.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_node/axi_response_block.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_slice.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/axi_slice_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/axi_spi_slave.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/axi_spi_slave_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice/axi_w_buffer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/boot_code.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/boot_rom_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/cluster_clock_inverter.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/cluster_clock_mux2.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/core2axi/core2axi.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/core2axi_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/core_region.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/generic_fifo.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_event_unit/generic_service_unit.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/instr_ram_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/periph_bus_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/peripherals.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/pulpino_top.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/ram_mux.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/rstgen.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_event_unit/sleep_unit.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/sp_ram_wrap.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_apb_if.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_clkgen.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_controller.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_fifo.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_rx.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_spi_master/spi_master_tx.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_controller.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_regs.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_rx.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_syncro.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_spi_slave/spi_slave_tx.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_timer/timer.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/apb_uart.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_clock_div.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_counter.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_edge_detect.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_fifo.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_input_filter.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_input_sync.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/slib_mv_filter.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/uart_baudgen.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/uart_interrupt.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/uart_receiver.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/ips/apb/apb_uart/uart_transmitter.vhd"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/clk_rst_gen.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_lint_defines.v"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/pulp_clock_inverter.sv"] \
 [file normalize "${origin_dir}/../../pulpino/rtl/components/pulp_clock_mux2.sv"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_dout.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_din.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_full_detector.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_token_ring.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_data_buffer.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/axi/axi_slice_dc/dc_synchronizer.v"] \
 [file normalize "${origin_dir}/../../pulpino/ips/adv_dbg_if/rtl/adbg_crc32.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/top/rtl/pulpemu_top.v" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../pulpino/ips/riscv/include/riscv_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/include/riscv_tracer_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/include/apu_core_package.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/cluster_clock_gating.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_L0_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_alu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_alu_div.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_apu_disp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_compressed_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_cs_registers.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_debug_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_decoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_ex_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_fetch_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_hwloop_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_hwloop_regs.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_id_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_if_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_int_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_load_store_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_mult.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_prefetch_L0_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_prefetch_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_register_file_latch.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/riscv/riscv_core.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_axi_biu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_axi_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adbg_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/adv_dbg_if/rtl/adv_dbg_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb2per/apb2per.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_event_unit/apb_event_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_fll_if/apb_fll_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_gpio/apb_gpio.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_i2c/i2c_master_defines.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_i2c/apb_i2c.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_node/apb_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_node/apb_node_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_pulpino/apb_pulpino.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/apb_spi_master.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_timer/apb_timer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi2apb/axi2apb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi2apb/axi2apb32.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/axi2apb_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_AR_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_AW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_ArbitrationTree.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_BR_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_BW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_DW_allocator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_FanInPrimitive_Req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_RR_Flag_Req.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_address_decoder_AR.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_address_decoder_AW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_address_decoder_BR.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_address_decoder_BW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_address_decoder_DW.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_ar_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_aw_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_b_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/axi_mem_if_SP_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_multiplexer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_node.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/axi_node_intf_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_r_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_request_block.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_node/axi_response_block.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_slice.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/axi_slice_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/axi_spi_slave.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/axi_spi_slave_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_slice/axi_w_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/boot_code.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/boot_rom_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/cluster_clock_inverter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/cluster_clock_mux2.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/core2axi/core2axi.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/core2axi_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/core_region.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/generic_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_event_unit/generic_service_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/instr_ram_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/periph_bus_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/peripherals.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/pulpino_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/ram_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/rstgen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_event_unit/sleep_unit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/sp_ram_wrap.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_apb_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_clkgen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_spi_master/spi_master_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_controller.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_regs.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_syncro.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/axi/axi_spi_slave/spi_slave_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_timer/timer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/apb_uart.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_clock_div.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_counter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_edge_detect.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_fifo.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_input_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_input_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/slib_mv_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/uart_baudgen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/uart_interrupt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/uart_receiver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/ips/apb/apb_uart/uart_transmitter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/clk_rst_gen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/pulp_clock_inverter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../../pulpino/rtl/components/pulp_clock_mux2.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "include_dirs" -value "[file normalize "$origin_dir/../../pulpino/rtl/includes"] [file normalize "$origin_dir/../../pulpino/ips/riscv/include"] [file normalize "$origin_dir/../../pulpino/ips/apb/apb_event_unit/include"] [file normalize "$origin_dir/../../pulpino/ips/axi/axi_node"]" -objects $obj
set_property -name "top" -value "pulpemu_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "PULP_FPGA_EMUL=1" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/ip/clk_wiz_0/clk_wiz_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_0/clk_wiz_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/ip/xilinx_mem_8192x32/xilinx_mem_8192x32.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "xilinx_mem_8192x32/xilinx_mem_8192x32.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/top/xdc/arty_pulpino.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "xdc/arty_pulpino.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files *xdc/arty_pulpino.xdc]" -objects $obj
set_property -name "target_part" -value "xc7a35tcsg324-1" -objects $obj
set_property -name "target_ucf" -value "[get_files *xdc/arty_pulpino.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "pulpemu_top" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a35tcsg324-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "synth_1_synth_report_utilization_0" -objects $obj

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a35tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a35tcsg324-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_init_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_opt_report_drc_0" -objects $obj

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_io_0" -objects $obj

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_utilization_0" -objects $obj

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_control_sets_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_1" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_post_place_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_drc_0" -objects $obj

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_methodology_0" -objects $obj

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_power_0" -objects $obj

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_route_status_0" -objects $obj

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_clock_utilization_0" -objects $obj

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_bus_skew_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_bus_skew_0" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a35tcsg324-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
set obj [get_dashboards default_dashboard]

# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
# Set current dashboard to 'default_dashboard' 
current_dashboard default_dashboard 
