# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kle/iBox/pr/pulp/pulpino/fpga/arty/arty.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32.xci
# IP: The module: 'xilinx_mem_8192x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kle/iBox/pr/pulp/pulpino/fpga/arty/arty.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mem_8192x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/kle/iBox/pr/pulp/pulpino/fpga/arty/arty.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32.xci
# IP: The module: 'xilinx_mem_8192x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kle/iBox/pr/pulp/pulpino/fpga/arty/arty.srcs/sources_1/ip/xilinx_mem_8192x32/xilinx_mem_8192x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mem_8192x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
